### ISSUE TITLE
Make authentication via header possible.

### ISSUE THREAD

**Issue by DebVortex** [transcode-de/durga#3] opened 2014-12-12 14:43 UTC
Currently, you could theoreticaly only use open APIs or APIs that allow logging in via params. Several APIs allow the use of the 'AUTHORISATION' header. There should be a way to use this, too.

**Comment by keimlink** [comment] 2015-01-08 17:09
This is a duplicate of #8.

**Closed as completed by keimlink** 2015-01-08 17:09 UTC
Labels: duplicate
